In [1]:
import numpy as np

In [2]:
np.__version__

'1.21.5'

# Creating Arrays

In [3]:
my_list=[0,1,2,3,4,5]
my_list

[0, 1, 2, 3, 4, 5]

In [4]:
type(my_list)

list

In [6]:
arr=np.array(my_list)

In [7]:
arr

array([0, 1, 2, 3, 4, 5])

In [8]:
type(arr)

numpy.ndarray

In [9]:
np.arange(5)

array([0, 1, 2, 3, 4])

In [10]:
np.arange(3.0)

array([0., 1., 2.])

In [11]:
np.arange(10) 

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,5)

array([0, 1, 2, 3, 4])

In [13]:
np.arange(10,20) 

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [14]:
np.arange(20,10) 

array([], dtype=int32)

In [15]:
np.arange(-20,10) 

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7,   8,   9])

In [16]:
np.arange(-16,10) 

array([-16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,  -4,
        -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,   9])

In [17]:
np.arange(-20,-10)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11])

In [18]:
np.arange(30,20)  # 1st arg always be < then 2nd arg

array([], dtype=int32)

In [19]:
b = np.arange(-30,20)
b

array([-30, -29, -28, -27, -26, -25, -24, -23, -22, -21, -20, -19, -18,
       -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,  -7,  -6,  -5,
        -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,   6,   7,   8,
         9,  10,  11,  12,  13,  14,  15,  16,  17,  18,  19])

In [20]:
np.arange(10,30,5)  # 10- starting from 30- end point 5 - step count

array([10, 15, 20, 25])

In [21]:
np.arange(0,10,3)

array([0, 3, 6, 9])

In [22]:
np.arange(10,30,5,1)

TypeError: Cannot interpret '1' as a data type

In [23]:
b1 = np.zeros(2) #parameter tunning
b1

array([0., 0.])

In [24]:
np.zeros(5,dtype=int) #hyperparameter tunning

array([0, 0, 0, 0, 0])

In [25]:
zero = np.zeros((2,2))
zero

array([[0., 0.],
       [0., 0.]])

In [26]:
np.zeros((10,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [27]:
np.zeros((2,10))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [28]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [29]:
np.zeros((3,3))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [30]:
np.zeros((10,30))

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0

In [31]:
np.zeros((5,10)) # bydefaul 1arge -- will give row & 2nd arg - columns

array([[0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0.]])

In [33]:
n = (5,7)
n1 = (6,8)
print(np.zeros(n)) # parameter tunnin g
#print(np.zeros(n1,dtype=int)) ## hypyerparameter tunning 

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


In [34]:
print(np.zeros(n1))

[[0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0.]]


In [35]:
np.ones(4,dtype=int)

array([1, 1, 1, 1])

In [36]:
np.ones(4)

array([1., 1., 1., 1.])

In [37]:
n

(5, 7)

In [38]:
np.ones(n)

array([[1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1., 1., 1.]])

In [39]:
np.ones((5,4),dtype=int) # by default 5- rows & 4 - columns

array([[1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [41]:
>>> from numpy import *
>>> arange(3)

array([0, 1, 2])

In [42]:
range(12)
list(range(12))

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [43]:
y = list(range(12))
y

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11]

In [44]:
np.

SyntaxError: invalid syntax (2469254449.py, line 1)

In [45]:
>>> from numpy import *
>>> zeros(5)

array([0., 0., 0., 0., 0.])

In [46]:
np.random.rand(4)

array([0.92508231, 0.98448077, 0.14534352, 0.29861976])

In [52]:
np.random.rand(2,4)

array([[0.61578338, 0.57246068, 0.50711246, 0.01584422],
       [0.12439517, 0.97095314, 0.90640923, 0.87940397]])

In [55]:
np.random.randint(2,20) # 2nd argument is exlusive 

19

In [59]:
np.random.randint(0,2)

1

In [60]:
np.random.randint(1,10,4)

array([5, 8, 8, 8])

In [64]:
np.random.randint(1,3,5)

array([2, 2, 1, 1, 2])

In [65]:
np.random.randint(30,20,10) 

ValueError: low >= high

In [67]:
np.random.randint(1)

0

In [73]:
np.random.randint(5,9)  #GET THE VALUE <=1 & >=5

6

In [80]:
np.random.randint(10,21,3)

array([14, 13, 18])

In [81]:
np.random.randint(1,12,10)

array([ 2, 10,  6,  9, 10,  1,  6,  5,  6,  8])

In [82]:
np.random.randint(10,40,(10,10)) #generre the element 10 -30 with 4*4 mtri

array([[36, 27, 25, 35, 12, 33, 10, 15, 33, 10],
       [12, 12, 20, 27, 32, 31, 18, 25, 27, 23],
       [17, 13, 20, 19, 12, 12, 27, 29, 20, 27],
       [17, 30, 24, 26, 35, 33, 18, 12, 38, 29],
       [29, 34, 38, 11, 20, 37, 35, 28, 34, 37],
       [10, 36, 19, 19, 16, 39, 14, 11, 21, 35],
       [26, 27, 10, 37, 16, 29, 19, 39, 17, 15],
       [14, 38, 21, 11, 19, 32, 20, 27, 18, 13],
       [30, 27, 21, 27, 31, 38, 35, 11, 31, 14],
       [29, 24, 13, 26, 18, 14, 20, 33, 13, 25]])

In [83]:
b = np.random.randint(10,20,(5,4))
b

array([[14, 14, 19, 19],
       [16, 18, 13, 12],
       [16, 13, 14, 19],
       [14, 16, 17, 15],
       [14, 18, 17, 19]])

In [84]:
b[:]

array([[14, 14, 19, 19],
       [16, 18, 13, 12],
       [16, 13, 14, 19],
       [14, 16, 17, 15],
       [14, 18, 17, 19]])

In [85]:
b[0:2]

array([[14, 14, 19, 19],
       [16, 18, 13, 12]])

In [86]:
b

array([[14, 14, 19, 19],
       [16, 18, 13, 12],
       [16, 13, 14, 19],
       [14, 16, 17, 15],
       [14, 18, 17, 19]])

In [87]:
b[0:-1]

array([[14, 14, 19, 19],
       [16, 18, 13, 12],
       [16, 13, 14, 19],
       [14, 16, 17, 15]])

In [88]:
b[0,2]

19

In [89]:
b

array([[14, 14, 19, 19],
       [16, 18, 13, 12],
       [16, 13, 14, 19],
       [14, 16, 17, 15],
       [14, 18, 17, 19]])

In [90]:
np.random.randint(10,20,(4,4))

array([[14, 18, 11, 19],
       [13, 11, 15, 17],
       [15, 11, 17, 12],
       [18, 16, 18, 13]])

# operations

In [91]:
a = np.random.randint(10,20,5)
a

array([14, 19, 13, 16, 15])

In [92]:
arr

array([0, 1, 2, 3, 4, 5])

In [93]:
arr2= np.random.randint(0,100,(10,10))

In [94]:
arr2

array([[59, 39, 47, 85, 25, 14, 47, 14, 13, 90],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [74, 77, 69, 51, 36, 72, 35, 97, 12, 36],
       [47, 23, 16, 37, 86, 85, 88, 39, 40, 22]])

In [95]:
arr

array([0, 1, 2, 3, 4, 5])

In [96]:
arr[:]

array([0, 1, 2, 3, 4, 5])

In [99]:
arr[:5]

array([0, 1, 2, 3, 4])

In [98]:
arr2[:]

array([[59, 39, 47, 85, 25, 14, 47, 14, 13, 90],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [74, 77, 69, 51, 36, 72, 35, 97, 12, 36],
       [47, 23, 16, 37, 86, 85, 88, 39, 40, 22]])

In [101]:
arr2[0:5]

array([[59, 39, 47, 85, 25, 14, 47, 14, 13, 90],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56]])

In [102]:
arr2

array([[59, 39, 47, 85, 25, 14, 47, 14, 13, 90],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [74, 77, 69, 51, 36, 72, 35, 97, 12, 36],
       [47, 23, 16, 37, 86, 85, 88, 39, 40, 22]])

In [103]:
arr2[1,5]

78

In [104]:
arr2[-5,5]

19

In [105]:
arr2[-5,-5]

19

In [106]:
arr2[-1,-2]

40

In [107]:
arr2

array([[59, 39, 47, 85, 25, 14, 47, 14, 13, 90],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [74, 77, 69, 51, 36, 72, 35, 97, 12, 36],
       [47, 23, 16, 37, 86, 85, 88, 39, 40, 22]])

In [108]:
arr2[::-1]

array([[47, 23, 16, 37, 86, 85, 88, 39, 40, 22],
       [74, 77, 69, 51, 36, 72, 35, 97, 12, 36],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [59, 39, 47, 85, 25, 14, 47, 14, 13, 90]])

In [109]:
arr2

array([[59, 39, 47, 85, 25, 14, 47, 14, 13, 90],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [74, 77, 69, 51, 36, 72, 35, 97, 12, 36],
       [47, 23, 16, 37, 86, 85, 88, 39, 40, 22]])

In [110]:
arr2[::-2]

array([[47, 23, 16, 37, 86, 85, 88, 39, 40, 22],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54]])

In [111]:
arr2

array([[59, 39, 47, 85, 25, 14, 47, 14, 13, 90],
       [35, 46, 83, 35, 98, 78, 89, 89,  2, 54],
       [50, 58, 89, 41, 11,  8, 62, 67, 73, 82],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [17,  5, 16, 99, 41, 28, 95, 44, 44, 56],
       [28, 51, 45, 69, 18, 19, 75, 32, 88, 67],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [41, 81, 63, 48, 47, 78, 47,  5, 39,  8],
       [74, 77, 69, 51, 36, 72, 35, 97, 12, 36],
       [47, 23, 16, 37, 86, 85, 88, 39, 40, 22]])

In [112]:
arr2[::-3]

array([[47, 23, 16, 37, 86, 85, 88, 39, 40, 22],
       [ 8, 28,  7, 80, 68,  1, 55, 19, 36, 77],
       [ 7, 20, 10, 70, 98, 14, 29, 53, 81, 82],
       [59, 39, 47, 85, 25, 14, 47, 14, 13, 90]])

In [114]:
arr

array([0, 1, 2, 3, 4, 5])

In [115]:
arr.max()

5

In [116]:
arr.min()

0

In [117]:
arr.mean()

2.5

In [118]:
>>> from numpy import *
>>> a = array([1,2,3,4,9])
>>> median(a)

3.0

In [123]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [124]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [125]:
arr.reshape(1,6)

array([[0, 1, 2, 3, 4, 5]])

In [126]:
arr.reshape(3,2,order='C')

array([[0, 1],
       [2, 3],
       [4, 5]])

In [129]:
arr.reshape(3,2,order='F')

array([[0, 3],
       [1, 4],
       [2, 5]])

In [130]:
arr

array([0, 1, 2, 3, 4, 5])

In [131]:
arr.reshape(2,3)

array([[0, 1, 2],
       [3, 4, 5]])

In [132]:
arr.reshape(1,4)  

ValueError: cannot reshape array of size 6 into shape (1,4)

In [133]:
arr.reshape(1,6) 

array([[0, 1, 2, 3, 4, 5]])

In [134]:
arr.reshape(6,1) 

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [135]:
arr.reshape(2,6)

ValueError: cannot reshape array of size 6 into shape (2,6)

In [136]:
arr.reshape(3,3) 

ValueError: cannot reshape array of size 6 into shape (3,3)

In [137]:
arr

array([0, 1, 2, 3, 4, 5])

In [138]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

# Indexing

In [139]:
mat = np.arange(0,100).reshape(10,10)

In [140]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [141]:
row=4
col=5

In [142]:
row

4

In [143]:
col

5

In [144]:
mat[row,col]

45

In [145]:
mat[4,5]

45

In [146]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [147]:
mat[:]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [148]:
col=6

In [149]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [150]:
mat[row,:]

array([40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [151]:
mat[:row]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [152]:
mat[row:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [153]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [154]:
mat[:,8]

array([ 8, 18, 28, 38, 48, 58, 68, 78, 88, 98])

In [155]:
mat[:,-1]

array([ 9, 19, 29, 39, 49, 59, 69, 79, 89, 99])

In [156]:
mat[:,col]

array([ 6, 16, 26, 36, 46, 56, 66, 76, 86, 96])

In [157]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [158]:
mat[1,4]

14

In [159]:
mat[1:4]

array([[10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [160]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [161]:
mat[3:-3]

array([[30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [162]:
mat[6:]

array([[60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [163]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [164]:
mat[:6]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [165]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [166]:
mat[5:7]

array([[50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69]])

In [167]:
mat[0:10:3]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [168]:
mat[4:]

array([[40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [169]:
mat[:4]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39]])

In [170]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [171]:
mat[::-1]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [172]:
mat[::-2]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19]])

In [173]:
mat[::-3]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9]])

In [174]:
mat[::-5]

array([[90, 91, 92, 93, 94, 95, 96, 97, 98, 99],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49]])

In [175]:
mat[2:6]

array([[20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59]])

In [176]:
mat[2:6,2:4] # 1:5 --> only row part /// 1:3 -- it indicates only column parts

array([[22, 23],
       [32, 33],
       [42, 43],
       [52, 53]])

In [177]:
mat[3:6,3:5]

array([[33, 34],
       [43, 44],
       [53, 54]])

In [178]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [179]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

In [180]:
mat[3:5,2:4,]

array([[32, 33],
       [42, 43]])

# Masking

In [181]:
mat

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14, 15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35, 36, 37, 38, 39],
       [40, 41, 42, 43, 44, 45, 46, 47, 48, 49],
       [50, 51, 52, 53, 54, 55, 56, 57, 58, 59],
       [60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79],
       [80, 81, 82, 83, 84, 85, 86, 87, 88, 89],
       [90, 91, 92, 93, 94, 95, 96, 97, 98, 99]])

In [182]:
id(mat)

2153125280048

In [183]:
mat<50

array([[ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [184]:
mat>50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True],
       [ True,  True,  True,  True,  True,  True,  True,  True,  True,
         True]])

In [185]:
mat==50

array([[False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [ True, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False],
       [False, False, False, False, False, False, False, False, False,
        False]])

In [186]:
mat[mat==50]

array([50])

In [187]:
a1 = mat[mat<50] 
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [188]:
a2 = mat[mat>50] 
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])

In [189]:
a4 = mat[mat==50]
a4

array([50])

In [190]:
a1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [191]:
a2

array([51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99])