In this notebook, learn how to apply Machine Learning models to Natural Language Processing (NLP).

We will work with Restaurant Reviews dataset (.tsv file) to predict a customer review whether it is positive or negative.

In [1]:
# Importing libraries
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

# Load dataset (TSV format → tab-separated values)
df= pd.read_csv(r"C:\Users\91700\Downloads\Restaurant_Reviews.tsv", delimiter = '\t', quoting = 3)


In [2]:
df

,Review,Liked
0,Wow... Loved this place.,1
1,Crust is not good.,0
2,Not tasty and the texture was just nasty.,0
3,Stopped by during the late May bank holiday of...,1
4,The selection on the menu was great and so wer...,1
...,...,...
995,I think food should have flavor and texture an...,0
996,Appetite instantly gone.,0
997,Overall I was not impressed and would not go b...,0
998,"The whole experience was underwhelming, and I ...",0


In [3]:
# Text Cleaning & Preprocessing
import re
import nltk
from nltk.corpus import stopwords
from nltk.stem.porter import PorterStemmer

corpus = []

for i in range(0, 1000):
    review = re.sub('[^a-zA-Z]', ' ', df['Review'][i])
    review = review.lower()
    review = review.split()
    ps = PorterStemmer()
    review = [ps.stem(word) for word in review if not word in set(stopwords.words('english'))]
    review = ' '.join(review)
    corpus.append(review)



In [4]:
corpus[:5]

['wow love place',
 'crust good',
 'tasti textur nasti',
 'stop late may bank holiday rick steve recommend love',
 'select menu great price']

In [5]:
# Feature Extraction (Bag of Words model)
from sklearn.feature_extraction.text import CountVectorizer
cv = CountVectorizer()
X = cv.fit_transform(corpus).toarray()
y= df.iloc[:,1].values

In [6]:
# Train/Test Split

from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.20, random_state=0)

In [7]:
# Train a Machine Learning Model (Decision Tree)

from sklearn.tree import DecisionTreeClassifier
classifier = DecisionTreeClassifier()
classifier.fit(X_train, y_train)

# Predictions
y_pred = classifier.predict(X_test)

# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n",cm)
print("Accuracy:",ac)

# Bias & Variance
bias = classifier.score(X_train, y_train)
variance = classifier.score(X_test, y_test)

print("Bias:",bias)
print("Variance:",variance)

Confusion Matrix:
 [[72 25]
 [39 64]]
Accuracy: 0.68
Bias: 0.99625
Variance: 0.68


In [8]:
# Train a Machine Learning Model(Random Forest)

from sklearn.ensemble import RandomForestClassifier
classifier = RandomForestClassifier()
classifier.fit(X_train, y_train)

# Predictions
y_pred = classifier.predict(X_test)

# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n",cm)
print("Accuracy:",ac)

# Bias & Variance
bias = classifier.score(X_train, y_train)
variance = classifier.score(X_test, y_test)

print("Bias:",bias)
print("Variance:",variance)

Confusion Matrix:
 [[84 13]
 [47 56]]
Accuracy: 0.7
Bias: 0.99625
Variance: 0.7


In [9]:
# Train a Machine Learning Model(Support Vector Machine)

from sklearn.svm import SVC
classifier = SVC(kernel='linear')
classifier.fit(X_train, y_train)

# Predictions
y_pred = classifier.predict(X_test)

# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n",cm)
print("Accuracy:",ac)

# Bias & Variance
bias = classifier.score(X_train, y_train)
variance = classifier.score(X_test, y_test)

print("Bias:",bias)
print("Variance:",variance)

Confusion Matrix:
 [[74 23]
 [33 70]]
Accuracy: 0.72
Bias: 0.98
Variance: 0.72


In [10]:
# Train a Machine Learning Model(Naive Bayes)

from sklearn.naive_bayes import MultinomialNB
classifier = MultinomialNB()
classifier.fit(X_train, y_train)

# Predictions
y_pred = classifier.predict(X_test)

# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n",cm)
print("Accuracy:",ac)

# Bias & Variance
bias = classifier.score(X_train, y_train)
variance = classifier.score(X_test, y_test)

print("Bias:",bias)
print("Variance:",variance)

Confusion Matrix:
 [[72 25]
 [22 81]]
Accuracy: 0.765
Bias: 0.94
Variance: 0.765


In [11]:
# Train a Machine Learning Model(Logistic Regression)

from sklearn.linear_model import LogisticRegression
classifier = LogisticRegression()
classifier.fit(X_train, y_train)

# Predictions
y_pred = classifier.predict(X_test)

# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n",cm)
print("Accuracy:",ac)

# Bias & Variance
bias = classifier.score(X_train, y_train)
variance = classifier.score(X_test, y_test)

print("Bias:",bias)
print("Variance:",variance)

Confusion Matrix:
 [[76 21]
 [37 66]]
Accuracy: 0.71
Bias: 0.9575
Variance: 0.71


In [12]:
# Train a Machine Learning Model(K-Nearest Neighbors)

from sklearn.neighbors import KNeighborsClassifier
classifier = KNeighborsClassifier()
classifier.fit(X_train, y_train)
# Predictions
y_pred = classifier.predict(X_test)

# Confusion Matrix
from sklearn.metrics import confusion_matrix, accuracy_score
cm = confusion_matrix(y_test, y_pred)
ac = accuracy_score(y_test, y_pred)

print("Confusion Matrix:\n",cm)
print("Accuracy:",ac)

# Bias & Variance
bias = classifier.score(X_train, y_train)
variance = classifier.score(X_test, y_test)

print("Bias:",bias)
print("Variance:",variance)

Confusion Matrix:
 [[80 17]
 [57 46]]
Accuracy: 0.63
Bias: 0.7925
Variance: 0.63
